filebeat.autodiscover:
  providers:
    - type: kubernetes
      templates:
        - condition:
           or:
             - and: 
                  - equals:
                      kubernetes.container.name: tensorflow
                  - equals:
                      kubernetes.labels.logger: filebeat
                  - equals:
                      kubernetes.node.name: NODENAME
             - and: 
                  - equals:
                      kubernetes.container.name: pytorch
                  - equals:
                      kubernetes.labels.logger: filebeat
                  - equals:
                      kubernetes.node.name: NODENAME

          config:
            - type: docker
              containers:
                  path: "DOCKERPATH"
                  ids:
                   - "${data.kubernetes.container.id}"
              fields:
                 tf_jobid: ${data.kubernetes.labels.tf-job-name:NotTfjob}
                 tf_role: ${data.kubernetes.labels.tf-replica-type:launcher}
                 tf_index: ${data.kubernetes.labels.tf-replica-index:0}
                 pt_jobid: ${data.kubernetes.labels.pt-job-name:NotPtjob}
                 pt_role: ${data.kubernetes.labels.pt-replica-type:master}
                 pt_index: ${data.kubernetes.labels.pt-replica-index:0}
              fields_under_root: true
processors:
   - drop_fields:
         fields: ["beat", "input", "prospector", "offset", "source", "labels", "host", "kubernetes", "pod", "container", "node", "tags", "@version","log","ecs","agent"]


output.logstash:
  hosts: ["logstash.dkube:5044"]
