apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: dkube
  labels:
    k8s-app: filebeat
data:
  filebeat.yml: |-
    # To enable hints based autodiscover, remove `filebeat.config.inputs` configuration and uncomment this:
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          templates:
            - condition:
               and:
                 - or:
                     - equals:
                          kubernetes.container.name: tensorflow
                     - equals:
                          kubernetes.container.name: datajob
                 - and:
                     - equals:
                         kubernetes.labels.logger: filebeat
                     - equals:
                         kubernetes.node.name: ${NODENAME}
              config:
                - type: docker
                  containers:
                      path: "DOCKERPATH"
                      ids:
                       - "${data.kubernetes.container.id}"
                  fields:
                     tfjobid: ${data.kubernetes.labels.jobuuid}
                     tfrole: ${data.kubernetes.labels.tf-replica-type:SINGLETON}
                     username: ${data.kubernetes.labels.username}
                     tfindex: ${data.kubernetes.labels.tf-replica-index:0}
                  fields_under_root: true

    processors:
      - drop_fields:
           fields: ["beat", "input", "prospector", "offset", "source", "labels", "host", "kubernetes", "pod", "container", "node", "tags", "@version","log","ecs","agent"]
            
    output.logstash:
      hosts: ["logstash.dkube:5044"]

