apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: dkube
  labels:
    app: logstash
data:
  logstash.conf: |-
    input{
      beats {
       port => 5044
      }
    }
    
    filter {
       mutate {
         add_field => {
            "[@metadata][jobuuid]"=> "%{[tfjobid]}"
            "[@metadata][role]"=> "%{[tfrole]}"
            "[@metadata][index]" => "%{[tfindex]}"
            "[@metadata][username]" => "%{[username]}"
          }
       }
    }

    output {
        file{
           path => "/var/log/dkube/%{[@metadata][username]}/%{[@metadata][jobuuid]}/logs.txt"
           codec => line{format => "%{@timestamp}  %{[@metadata][role]}-%{[@metadata][index]}  %{message}"}
         }
    }

